target :app do
  signature "sig/generated"
  signature "sig/rbs_rails"
  signature "sig/manual"

  check "app"
  check "lib"

  # spec/ は RSpec の DSL、config/ は Rails の設定 DSL で型付けの投資対効果が低いため対象外にする
end
